(() => {
  "use strict";
  const KEYS={clients:"barbearia_clientes",appointments:"barbearia_agendamentos",payments:"barbearia_pagamentos"};
  const read=(key,fallback=[])=>{try{const v=JSON.parse(localStorage.getItem(key)||"null");return v??fallback}catch{return fallback}};
  const list=key=>{const v=read(key,[]);return Array.isArray(v)?v:[]};
  const write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
  const norm=v=>String(v||"").trim().toLowerCase();
  const canceled=x=>["cancelado","cancelada","canceled"].includes(norm(x.status));
  const served=x=>["concluido","concluida","atendido","atendida"].includes(norm(x.status));
  const dateOf=v=>{if(!v)return null;if(/^\d{4}-\d{2}-\d{2}$/.test(String(v))){const [y,m,d]=String(v).split("-").map(Number);return new Date(y,m-1,d)}const d=new Date(v);return Number.isNaN(d.getTime())?null:d};
  const keyDate=v=>{const d=dateOf(v);return d?[d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-"):""};
  const money=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)||0);
  const fmt=v=>{const d=dateOf(v);return d?new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"2-digit",year:"numeric"}).format(d):"—"};
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  const daysAgo=v=>{const d=dateOf(v),now=new Date();if(!d)return Infinity;return Math.floor((new Date(now.getFullYear(),now.getMonth(),now.getDate())-new Date(d.getFullYear(),d.getMonth(),d.getDate()))/86400000)};
  const appointmentsFor=client=>list(KEYS.appointments).filter(a=>(
    (client.id&&a.clientId===client.id) ||
    (client.name&&norm(a.clientName||a.clienteNome)===norm(client.name) && (!client.phone||!a.clientPhone||String(a.clientPhone).replace(/\D/g,"")===String(client.phone).replace(/\D/g,"")))
  ));
  const paymentsFor=client=>list(KEYS.payments).filter(p=>!["cancelado","cancelada","estornado","estornada"].includes(norm(p.status))&&(
    (client.id&&p.clientId===client.id)||(client.name&&norm(p.clientName||p.clienteNome)===norm(client.name))
  ));
  const metrics=client=>{const ap=appointmentsFor(client), done=ap.filter(served);const dates=done.map(a=>dateOf(a.date||a.start)).filter(Boolean).sort((a,b)=>a-b);const last=dates.at(-1)||null;const total=paymentsFor(client).reduce((s,p)=>s+(Number(p.amount??p.valor??p.value)||0),0);return{appointments:ap,done,last,total,count:done.length}};
  const status=client=>{const m=metrics(client);if(!m.last)return"Novo";const age=daysAgo(m.last);if(age<=30)return"Novo";if(age<=60)return"Ativo";return"Inativo"};
  const filtered=()=>{const clients=list(KEYS.clients),q=norm(document.querySelector("#client-search").value),filter=document.querySelector("#client-filter").value;return clients.filter(c=>{const m=metrics(c),s=status(c),text=norm(c.name+" "+(c.phone||""));return(!q||text.includes(q))&&(filter==="todos"||(filter==="novos"&&s==="Novo")||(filter==="ativos"&&s==="Ativo")||(filter==="inativos"&&s==="Inativo"))}).sort((a,b)=>norm(a.name).localeCompare(norm(b.name)))};
  const render=()=>{const clients=list(KEYS.clients),now=new Date();let fresh=0,active=0,inactive=0;clients.forEach(c=>{const s=status(c);if(s==="Novo")fresh++;if(s==="Ativo")active++;if(s==="Inativo")inactive++});document.querySelector("#total-clients").textContent=clients.length;document.querySelector("#new-clients").textContent=fresh;document.querySelector("#active-clients").textContent=active;document.querySelector("#inactive-clients").textContent=inactive;const box=document.querySelector("#clients-list"),rows=filtered();if(!rows.length){box.innerHTML='<div class="empty-clients"><span aria-hidden="true">👤</span><strong>Nenhum cliente encontrado</strong><p>Cadastre um cliente ou ajuste os filtros da busca.</p></div>';return}box.innerHTML=rows.map(c=>{const m=metrics(c),s=status(c);return '<article class="client-row"><div class="client-main"><strong>'+esc(c.name)+'</strong><small>'+esc(c.phone||"WhatsApp não informado")+'</small></div><div class="client-metric"><span>Última visita</span><strong>'+fmt(m.last)+'</strong></div><div class="client-metric"><span>Atendimentos</span><strong>'+m.done.length+'</strong></div><div class="client-metric"><span>Total gasto</span><strong>'+money(m.total)+'</strong></div><span class="client-status">'+s+'</span><div class="client-actions"><button class="text-button" type="button" data-action="history" data-id="'+esc(c.id)+'">Histórico</button><button class="text-button" type="button" data-action="edit" data-id="'+esc(c.id)+'">Editar</button><button class="text-button" type="button" data-action="delete" data-id="'+esc(c.id)+'">Excluir</button></div></article>'}).join("")};
  const openForm=client=>{const form=document.querySelector("#client-form");form.reset();form.elements.id.value=client?.id||"";form.elements.name.value=client?.name||"";form.elements.phone.value=client?.phone||"";form.elements.preferences.value=client?.preferences||"";form.elements.notes.value=client?.notes||"";document.querySelector("#client-dialog-title").textContent=client?"Editar cliente":"Novo cliente";document.querySelector("#client-form-error").textContent="";document.querySelector("#client-dialog").showModal()};
  const save=e=>{e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f).entries()),name=d.name.trim(),phone=d.phone.trim(),clients=list(KEYS.clients);if(!name){document.querySelector("#client-form-error").textContent="Informe o nome do cliente.";return}const duplicate=clients.some(c=>c.id!==d.id&&norm(c.name)===norm(name)&&String(c.phone||"").replace(/\D/g,"")===String(phone).replace(/\D/g,"")&&phone);if(duplicate){document.querySelector("#client-form-error").textContent="Este cliente já está cadastrado.";return}const old=clients.find(c=>c.id===d.id),record={id:d.id||"cli-"+Date.now(),name,phone,preferences:d.preferences.trim(),notes:d.notes.trim(),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};const i=clients.findIndex(c=>c.id===record.id);if(i>=0)clients[i]=record;else clients.push(record);write(KEYS.clients,clients);document.querySelector("#client-dialog").close();render()};
  const history=client=>{const m=metrics(client);document.querySelector("#history-title").textContent=client.name;document.querySelector("#history-summary").innerHTML='<div><span>Atendimentos</span><strong>'+m.done.length+'</strong></div><div><span>Última visita</span><strong>'+fmt(m.last)+'</strong></div><div><span>Total gasto</span><strong>'+money(m.total)+'</strong></div>';const items=m.appointments.slice().sort((a,b)=>String(b.date||b.start).localeCompare(String(a.date||a.start))).slice(0,30);document.querySelector("#history-list").innerHTML=items.length?items.map(a=>'<div class="history-item"><div><strong>'+esc(a.serviceName||a.servicoNome||"Atendimento")+'</strong><small>'+fmt(a.date||a.start)+(a.time?" às "+esc(a.time):"")+'</small></div><strong>'+esc(a.status||"Agendado")+'</strong></div>').join(""):'<div class="empty-clients"><strong>Nenhum atendimento registrado</strong><p>O histórico aparecerá conforme os atendimentos forem cadastrados.</p></div>';document.querySelector("#history-dialog").showModal()};
  document.addEventListener("DOMContentLoaded",()=>{render();document.querySelector("#new-client").addEventListener("click",()=>openForm());document.querySelector("#client-search").addEventListener("input",render);document.querySelector("#client-filter").addEventListener("change",render);document.querySelector("#client-form").addEventListener("submit",save);document.querySelector("#cancel-client-dialog").addEventListener("click",()=>document.querySelector("#client-dialog").close());document.querySelector("#close-client-dialog").addEventListener("click",()=>document.querySelector("#client-dialog").close());document.querySelector("#close-history-dialog").addEventListener("click",()=>document.querySelector("#history-dialog").close());document.querySelector("#clients-list").addEventListener("click",e=>{const b=e.target.closest("[data-action]");if(!b)return;const c=list(KEYS.clients).find(x=>x.id===b.dataset.id);if(!c)return;if(b.dataset.action==="history")history(c);if(b.dataset.action==="edit")openForm(c);if(b.dataset.action==="delete"&&window.confirm("Excluir este cliente do cadastro? O histórico de agendamentos será preservado.")){write(KEYS.clients,list(KEYS.clients).filter(x=>x.id!==c.id));render()}})});
})();